services:
  profile-frontend:
    container_name: profile-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_PROFILE_BACKEND_URL: ${VITE_PROFILE_BACKEND_URL:-}
        VITE_CHAT_SERVICE_URL: ${VITE_CHAT_SERVICE_URL:-}
    ports:
      - "80:80"
    networks:
      - portfolio-network
    restart: always

networks:
  portfolio-network:
    external: true
